insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/168x100.png/5fa2dd/ffffff', 'Nikaniki Copozio', 56, 81, 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/197x100.png/cc0000/ffffff', 'Rodger Whelpton', 27, 135, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/171x100.png/5fa2dd/ffffff', 'Rosaline Worner', 37, 149, 'Suspendisse potenti.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/210x100.png/ff4444/ffffff', 'Gregg Paulig', 19, 132, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/238x100.png/ff4444/ffffff', 'Beaufort Cluer', 24, 89, 'Suspendisse potenti. In eleifend quam a odio.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/116x100.png/ff4444/ffffff', 'Tam Tutchell', 54, 109, 'Nulla nisl. Nunc nisl.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/215x100.png/5fa2dd/ffffff', 'Verne Wakley', 51, 139, 'Praesent id massa id nisl venenatis lacinia.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/190x100.png/cc0000/ffffff', 'Lara Lipyeat', 31, 80, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/238x100.png/dddddd/000000', 'Dierdre Do Rosario', 51, 96, 'Aliquam erat volutpat. In congue. Etiam justo.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/201x100.png/cc0000/ffffff', 'Eleni Mirralls', 51, 139, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/166x100.png/ff4444/ffffff', 'Estevan Stook', 43, 136, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/189x100.png/dddddd/000000', 'Rita Askin', 43, 148, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/137x100.png/dddddd/000000', 'Paige Kless', 21, 96, 'Nulla tellus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/200x100.png/dddddd/000000', 'Helaina Stillmann', 49, 75, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/200x100.png/ff4444/ffffff', 'Juliann Spurdon', 54, 112, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/128x100.png/cc0000/ffffff', 'Adrianne Bodd', 34, 123, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/244x100.png/ff4444/ffffff', 'Eula Ravenscraft', 38, 110, 'Donec posuere metus vitae ipsum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/245x100.png/5fa2dd/ffffff', 'Henrieta Ebanks', 58, 122, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/173x100.png/dddddd/000000', 'Buffy Naisbit', 37, 136, 'Duis at velit eu est congue elementum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/213x100.png/cc0000/ffffff', 'Boone Keenlyside', 20, 109, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/179x100.png/5fa2dd/ffffff', 'Tina Dade', 48, 111, 'Integer ac neque.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/129x100.png/cc0000/ffffff', 'Trumaine Logan', 52, 129, 'Donec dapibus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/113x100.png/cc0000/ffffff', 'Antonio Gudd', 43, 71, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/143x100.png/cc0000/ffffff', 'Sarine Gatland', 37, 141, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/216x100.png/cc0000/ffffff', 'Kalila Frangione', 49, 146, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/167x100.png/ff4444/ffffff', 'Ravi Prise', 40, 78, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/120x100.png/cc0000/ffffff', 'Dalton Emblow', 55, 138, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/120x100.png/5fa2dd/ffffff', 'Karyl Gaddie', 56, 109, 'Nulla suscipit ligula in lacus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/112x100.png/5fa2dd/ffffff', 'Ade Ochterlony', 44, 79, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/206x100.png/ff4444/ffffff', 'Egor Killeen', 23, 145, 'Curabitur gravida nisi at nibh.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/177x100.png/ff4444/ffffff', 'Leeland Pendlebury', 60, 112, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/215x100.png/ff4444/ffffff', 'Ric Doni', 36, 134, 'Maecenas rhoncus aliquam lacus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/138x100.png/ff4444/ffffff', 'Symon Turone', 42, 133, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/149x100.png/cc0000/ffffff', 'Phylys Gutch', 24, 109, 'Nulla ac enim.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/206x100.png/dddddd/000000', 'Theda Bownde', 51, 138, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/101x100.png/5fa2dd/ffffff', 'Loreen Cordrey', 35, 77, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/218x100.png/cc0000/ffffff', 'Dyann Hutson', 56, 145, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/140x100.png/5fa2dd/ffffff', 'Adoree Marler', 58, 147, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/181x100.png/cc0000/ffffff', 'Shelly Fortnon', 35, 81, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/200x100.png/5fa2dd/ffffff', 'Franny Podbury', 34, 142, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/207x100.png/5fa2dd/ffffff', 'Tova Tukely', 25, 78, 'Morbi non quam nec dui luctus rutrum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/123x100.png/cc0000/ffffff', 'Waldo Plunkett', 46, 72, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/239x100.png/5fa2dd/ffffff', 'Alyce Jansens', 58, 128, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/136x100.png/ff4444/ffffff', 'Fiann Kayser', 46, 123, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/231x100.png/5fa2dd/ffffff', 'Briana Anthona', 44, 100, 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/114x100.png/cc0000/ffffff', 'Prent Embleton', 57, 141, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/211x100.png/dddddd/000000', 'Mary Meatyard', 32, 76, 'Morbi non lectus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/120x100.png/dddddd/000000', 'Christen Melburg', 34, 131, 'Maecenas rhoncus aliquam lacus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/146x100.png/dddddd/000000', 'Emmet Pithcock', 39, 127, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/102x100.png/cc0000/ffffff', 'Joyce Shilleto', 44, 100, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/239x100.png/dddddd/000000', 'Denis Echalie', 23, 79, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/211x100.png/5fa2dd/ffffff', 'Aida Burner', 38, 103, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/124x100.png/dddddd/000000', 'Geneva Thorrold', 50, 75, 'Suspendisse potenti.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/194x100.png/ff4444/ffffff', 'Merrielle Sharland', 52, 132, 'Morbi porttitor lorem id ligula.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/107x100.png/dddddd/000000', 'Tamarah Foy', 35, 88, 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/109x100.png/cc0000/ffffff', 'Felicio Pentercost', 34, 89, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/187x100.png/ff4444/ffffff', 'Briano Snooks', 36, 95, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/228x100.png/dddddd/000000', 'Ches Cable', 18, 85, 'In congue. Etiam justo.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/179x100.png/5fa2dd/ffffff', 'Corbin Langhorn', 53, 145, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/121x100.png/cc0000/ffffff', 'Fawn Niesegen', 56, 96, 'Morbi quis tortor id nulla ultrices aliquet.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/101x100.png/dddddd/000000', 'Karie Lowen', 23, 136, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/134x100.png/ff4444/ffffff', 'Luelle Sacco', 25, 104, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/236x100.png/ff4444/ffffff', 'Cassandry Middle', 26, 79, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/177x100.png/ff4444/ffffff', 'Ashton Gawn', 23, 147, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/111x100.png/dddddd/000000', 'Selena Biggerdike', 45, 91, 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/198x100.png/5fa2dd/ffffff', 'Marie-ann Poile', 43, 90, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/112x100.png/cc0000/ffffff', 'Max Inkles', 25, 95, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/151x100.png/cc0000/ffffff', 'Leigh Kenwell', 19, 71, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/105x100.png/5fa2dd/ffffff', 'Jessee MacCawley', 52, 80, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/106x100.png/dddddd/000000', 'Bobina Kelly', 58, 117, 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/119x100.png/cc0000/ffffff', 'Jayne Dorro', 22, 145, 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/184x100.png/5fa2dd/ffffff', 'Collen Mil', 48, 91, 'Nulla suscipit ligula in lacus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/108x100.png/ff4444/ffffff', 'Sean McDaid', 37, 90, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/174x100.png/ff4444/ffffff', 'Markus Mullany', 50, 75, 'Aenean fermentum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/102x100.png/5fa2dd/ffffff', 'Ame Grier', 23, 88, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/112x100.png/dddddd/000000', 'Jackelyn Bignold', 55, 84, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/250x100.png/dddddd/000000', 'Jeffy Stawell', 51, 72, 'Phasellus sit amet erat.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/142x100.png/ff4444/ffffff', 'Marleen Bool', 58, 73, 'In congue.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/248x100.png/dddddd/000000', 'Jerrylee Jessop', 42, 131, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/237x100.png/ff4444/ffffff', 'Farica Pedican', 56, 72, 'Duis mattis egestas metus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/166x100.png/5fa2dd/ffffff', 'Sally Rhodus', 51, 145, 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/192x100.png/5fa2dd/ffffff', 'Minny Trowler', 54, 110, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/140x100.png/ff4444/ffffff', 'Fidela Murphey', 51, 126, 'Curabitur in libero ut massa volutpat convallis.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/218x100.png/ff4444/ffffff', 'Husein Rossetti', 28, 76, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/158x100.png/ff4444/ffffff', 'Brendis Eberdt', 33, 77, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/179x100.png/ff4444/ffffff', 'Newton Pretswell', 25, 132, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/162x100.png/5fa2dd/ffffff', 'Pearla Cartan', 55, 71, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/105x100.png/5fa2dd/ffffff', 'Munmro Sparrowhawk', 59, 79, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/194x100.png/dddddd/000000', 'Quinn Ducket', 31, 77, 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/108x100.png/5fa2dd/ffffff', 'Steffen Arrault', 31, 142, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/143x100.png/5fa2dd/ffffff', 'Frank Clatworthy', 38, 132, 'Nulla tellus. In sagittis dui vel nisl.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/144x100.png/ff4444/ffffff', 'Craig Guirard', 29, 121, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/248x100.png/ff4444/ffffff', 'Leigh Martini', 59, 112, 'Pellentesque viverra pede ac diam.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/131x100.png/ff4444/ffffff', 'Nollie Arington', 50, 145, 'Morbi quis tortor id nulla ultrices aliquet.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/132x100.png/ff4444/ffffff', 'Reider Craigs', 29, 134, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/202x100.png/cc0000/ffffff', 'Emelda Frow', 38, 144, 'Integer tincidunt ante vel ipsum.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/135x100.png/5fa2dd/ffffff', 'Wheeler Spur', 43, 81, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/101x100.png/cc0000/ffffff', 'Marybelle Tunny', 49, 102, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/222x100.png/dddddd/000000', 'Joana Bickerdike', 54, 107, 'Suspendisse potenti.');
insert into characters (image, name, age, peso, history) values ('http://dummyimage.com/173x100.png/dddddd/000000', 'Anne-marie Glasman', 50, 109, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');


insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/110x100.png/dddddd/000000', 'Fixflex', '2016-04-08', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/126x100.png/cc0000/ffffff', 'Redhold', '2021-07-04', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/121x100.png/dddddd/000000', 'Zaam-Dox', '2016-06-29', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/114x100.png/cc0000/ffffff', 'Flowdesk', '2019-10-16', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/146x100.png/5fa2dd/ffffff', 'Flowdesk', '2017-09-26', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/179x100.png/5fa2dd/ffffff', 'Viva', '2022-09-30', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/233x100.png/dddddd/000000', 'Stringtough', '2018-02-02', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/152x100.png/cc0000/ffffff', 'Treeflex', '2016-08-01', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/118x100.png/cc0000/ffffff', 'Lotlux', '2017-04-29', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/141x100.png/dddddd/000000', 'Cardify', '2017-12-04', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/133x100.png/ff4444/ffffff', 'Opela', '2019-11-21', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/198x100.png/ff4444/ffffff', 'Solarbreeze', '2016-11-22', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/110x100.png/dddddd/000000', 'Trippledex', '2017-05-28', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/129x100.png/5fa2dd/ffffff', 'Zaam-Dox', '2019-10-03', 4);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/202x100.png/ff4444/ffffff', 'Y-find', '2017-11-09', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/226x100.png/cc0000/ffffff', 'Tres-Zap', '2020-02-21', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/163x100.png/5fa2dd/ffffff', 'Lotstring', '2018-08-04', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/243x100.png/ff4444/ffffff', 'Stringtough', '2020-06-20', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/126x100.png/5fa2dd/ffffff', 'Andalax', '2021-11-26', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/164x100.png/5fa2dd/ffffff', 'Trippledex', '2018-12-08', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/235x100.png/5fa2dd/ffffff', 'Domainer', '2021-09-10', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/118x100.png/5fa2dd/ffffff', 'Zaam-Dox', '2022-01-01', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/127x100.png/cc0000/ffffff', 'Holdlamis', '2019-03-28', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/193x100.png/cc0000/ffffff', 'Fintone', '2018-09-02', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/138x100.png/5fa2dd/ffffff', 'Domainer', '2021-04-16', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/185x100.png/5fa2dd/ffffff', 'Holdlamis', '2021-08-18', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/127x100.png/ff4444/ffffff', 'Sonair', '2020-07-18', 4);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/227x100.png/dddddd/000000', 'Tempsoft', '2021-11-22', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/236x100.png/5fa2dd/ffffff', 'Tres-Zap', '2018-09-27', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/156x100.png/ff4444/ffffff', 'Job', '2021-12-06', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/128x100.png/cc0000/ffffff', 'Veribet', '2016-06-18', 4);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/142x100.png/cc0000/ffffff', 'Tres-Zap', '2017-04-08', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/136x100.png/ff4444/ffffff', 'Bigtax', '2016-11-11', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/188x100.png/dddddd/000000', 'Vagram', '2019-09-22', 4);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/103x100.png/cc0000/ffffff', 'Voyatouch', '2016-04-02', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/159x100.png/dddddd/000000', 'Andalax', '2022-04-30', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/199x100.png/ff4444/ffffff', 'Tresom', '2019-12-02', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/209x100.png/cc0000/ffffff', 'Keylex', '2021-06-02', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/177x100.png/cc0000/ffffff', 'Tres-Zap', '2017-10-05', 4);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/228x100.png/dddddd/000000', 'Y-find', '2015-05-14', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/183x100.png/ff4444/ffffff', 'Pannier', '2022-11-06', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/185x100.png/ff4444/ffffff', 'Home Ing', '2019-12-26', 3);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/184x100.png/dddddd/000000', 'Tampflex', '2017-09-07', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/201x100.png/dddddd/000000', 'Tresom', '2022-09-04', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/175x100.png/ff4444/ffffff', 'Fintone', '2020-02-26', 5);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/103x100.png/dddddd/000000', 'Kanlam', '2022-04-29', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/239x100.png/ff4444/ffffff', 'Sonair', '2019-09-21', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/143x100.png/dddddd/000000', 'Viva', '2020-11-27', 1);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/102x100.png/5fa2dd/ffffff', 'Gembucket', '2018-01-05', 2);
insert into movies (image, title, create_date, qualification) values ('http://dummyimage.com/187x100.png/dddddd/000000', 'Viva', '2022-11-04', 4);




insert into characters_movies (id_character, id_movie) values (20, 13);
insert into characters_movies (id_character, id_movie) values (18, 4);
insert into characters_movies (id_character, id_movie) values (2, 9);
insert into characters_movies (id_character, id_movie) values (2, 10);
insert into characters_movies (id_character, id_movie) values (22, 8);
insert into characters_movies (id_character, id_movie) values (8, 22);
insert into characters_movies (id_character, id_movie) values (21, 13);
insert into characters_movies (id_character, id_movie) values (11, 7);
insert into characters_movies (id_character, id_movie) values (3, 22);
insert into characters_movies (id_character, id_movie) values (21, 11);
insert into characters_movies (id_character, id_movie) values (9, 12);
insert into characters_movies (id_character, id_movie) values (24, 22);
insert into characters_movies (id_character, id_movie) values (3, 4);
insert into characters_movies (id_character, id_movie) values (9, 14);
insert into characters_movies (id_character, id_movie) values (22, 13);
insert into characters_movies (id_character, id_movie) values (22, 5);
insert into characters_movies (id_character, id_movie) values (2, 6);
insert into characters_movies (id_character, id_movie) values (22, 11);
insert into characters_movies (id_character, id_movie) values (14, 11);
insert into characters_movies (id_character, id_movie) values (18, 16);
insert into characters_movies (id_character, id_movie) values (9, 7);
insert into characters_movies (id_character, id_movie) values (16, 23);
insert into characters_movies (id_character, id_movie) values (24, 14);
insert into characters_movies (id_character, id_movie) values (22, 19);
insert into characters_movies (id_character, id_movie) values (2, 25);
insert into characters_movies (id_character, id_movie) values (20, 20);
insert into characters_movies (id_character, id_movie) values (25, 4);
insert into characters_movies (id_character, id_movie) values (9, 21);
insert into characters_movies (id_character, id_movie) values (6, 24);
insert into characters_movies (id_character, id_movie) values (19, 8);
insert into characters_movies (id_character, id_movie) values (3, 3);
insert into characters_movies (id_character, id_movie) values (12, 23);
insert into characters_movies (id_character, id_movie) values (24, 19);
insert into characters_movies (id_character, id_movie) values (20, 12);
insert into characters_movies (id_character, id_movie) values (18, 6);
insert into characters_movies (id_character, id_movie) values (5, 1);
insert into characters_movies (id_character, id_movie) values (21, 4);
insert into characters_movies (id_character, id_movie) values (11, 25);
insert into characters_movies (id_character, id_movie) values (23, 23);
insert into characters_movies (id_character, id_movie) values (8, 13);
insert into characters_movies (id_character, id_movie) values (20, 5);
insert into characters_movies (id_character, id_movie) values (4, 18);
insert into characters_movies (id_character, id_movie) values (18, 10);
insert into characters_movies (id_character, id_movie) values (19, 21);
insert into characters_movies (id_character, id_movie) values (11, 17);
insert into characters_movies (id_character, id_movie) values (10, 6);
insert into characters_movies (id_character, id_movie) values (6, 7);
insert into characters_movies (id_character, id_movie) values (4, 12);
insert into characters_movies (id_character, id_movie) values (12, 3);
